### ISSUE TITLE
Migrate the whole shebang to Gatsby

### ISSUE THREAD

**Issue by TheHappyKoala** [TheHappyKoala/Harmony-of-the-Spheres#111]
https://github.com/TheHappyKoala/Harmony-of-the-Spheres/tree/migrate_to_gatsby

**Comment by TheHappyKoala** [comment]
@HugoGranstrom 

How you doing? Surviving the cold? Enjoying school?

I'm mighty busy with my new job, but I'm still working on HOS when I've got some time to spare. Just pushed the seed of what will be the Gatsby version of HOS: https://gravitysimulator.org/

Look at them pretty urls, lazy loaded images and what have you. Got quite a bit of stuff to fix/add, but it's gonna be a solid improvement.

**Comment by HugoGranstrom** [comment]
I'm doing fine, but school is keeping me very busy 😅 Thankfully I enjoy school otherwise this would have been horrible 😂 How are you? 😁 Christmas is nearing 🎅 have you stocked up on lights and cookies? 
What do you do in your day to day work? 😊 

The gatsby stuff looks fascinating 😉👍 I've gotten to use my Javascript experience from HOS at school. My section/program has a website and we are a group of around 15 students who are responsible for it and it is very fun. We meet each week to chill and program. We haven't really made any huge achievements yet but the aim is to rewrite the whole site in Vue.js (think it's in Laravell now). So I'm really grateful for the experience I have gotten from collaborating with you 😁😊😄 

When the christmas break arrives I will hopefully have more time help you out here 😅

**Comment by TheHappyKoala** [comment]
I'll tell you what I've stocked up on... Julmust 😄 !!! Love that stuff. But I'm doing really well. Looking forward to midwinter solstice and the days getting brighter again. 

Yaaaayyy, that's super cool that you get to put your JS skills to good use. Dabbled a little bit with VUE and it seems pretty cool - let me know how you like it once you've gotten started with the migration! Think Laravel is a php framework. Never worked with it, though. Is there a backend, and if so what is it written in? 

I work as a front-end developer, so I'm mainly implementing user interfaces that have been designed by our designers. It's a huge code base and the repository I'm working on has a 9 year long history and 58 000 something commits. The stack is React and some legacy backbone components with the state managed by a custom event bus. Everything that we write has to be both unit and end to end tested, which is cool. I'm gonna learn a great deal in my job, I'm pretty sure. 

Sweet! Hopefully I will have tied up the loose ends by xmas and maybe even resumed work on the spaceflight stuff... 🚀 🚀 🚀 

Be cool, stay in school 😄

**Comment by HugoGranstrom** [comment]
Great to hear! 😄 Yeah, it's crazy dark right now, the snow that fell last night did brighten it up a bit though ❄️. Tbh I've come to like julmust less by every year 😅 I don't know why but it doesn't spark the same feeling anymore.

We have made a few small projects in Vue thus far and it has been a nice experience. I feel like there are a few too many ways to do a certain task (I really like Python's "There should be one-- and preferably only one --obvious way to do it.", followed up by "Although that way may not be obvious at first unless you're Dutch." 🤣). But otherwise, I really like the concept of components and modularity. As far as I know, it tries to combine the best of both worlds (React + Angular) so it should have a few similarities to React. I think the backend is written in PHP (sadly 😓). We are trying to do as much as possible in the frontend so hopefully, we shouldn't need it for much else than database related stuff. 

Woho that sounds like a awesome job! 😃 That's a massive project! 😲 Think of how many people it is a legacy of, and now you are one of them. Testing is so underrated in my opinion. It is so much easier to catch stupid bugs if you test all your functions (automatically of course). 

No hurry what so ever 😉😄 Space will stay right where it is for a couple billion years 🤣

**Comment by TheHappyKoala** [comment]
@HugoGranstrom This is pretty cool. I've started toying around with your Lambert Solver and used it to recreate the trajectory of the Ulysses's spacecraft to Jupiter and subsequent gravity assist which brought it into a highly inclined and eccentric orbit over the poles of the Sun. I used HORIZONS to get the exact position of the spacecraft when it encountered Jupiter and its starting position around Earth, and then I fed this data alongside the time it took the craft to get to Jupiter into the planFlight method to get the velocity vectors and voila... It's a carbon copy of the spacecraft's actual orbit 🚀 ! 

The simulation:

https://gravitysimulator.org/spaceflight/ulysses

Orbit gif on Wikipedia:

https://en.wikipedia.org/wiki/Ulysses_(spacecraft)#/media/File:Animation_of_Ulysses_trajectory.gif

Said it before and I'll say it again; props to you!

**Comment by HugoGranstrom** [comment]
- Wow that's really cool 😮😉👍🚀🚀🚀 And I was amazed at how quick the simulation was, while still handling the gravity assist! I thought you used the all mighty RKN12 but to my happy suprise it was PEFRL! (Tried it with RKN12 as well but the old freezing bug seems to remain 😅). 

Once again, it's amazing what you can do with a browser today! 🚀😄

**Comment by HugoGranstrom** [comment]
The new gui works like a charm on mobile as well 😉 good work! 🚀😄

**Comment by TheHappyKoala** [comment]
https://github.com/TheHappyKoala/Harmony-of-the-Spheres/issues/112 - won't forget about this one now :D

**Comment by HugoGranstrom** [comment]
Awesome! :-D

**Comment by TheHappyKoala** [comment]
And thanks, still lots of work to be done, though, but I like it. By the way, I'm revamping the credits section; if you want to you can create a markdown file with information about your contributions to the project and any links you'd like to point people to . 🚀

**Comment by TheHappyKoala** [comment]
And happy Lucia... And Friday 🎆

**Comment by HugoGranstrom** [comment]
Happy Lucia to you too! 🕯️😊 Today my Christmas break begins so in a few days when I've got some rest and had some time for recreation I'll check back here to see what I can do 😉 

There's not really much to say about my contributions, it's just the integrators and the Lambert Solver. It can be written in a sentence 😅 short and concise

**Comment by HugoGranstrom** [comment]
Merry Christmas Darrell!! 🎅🎄🎁🎁🎄🎄🎅

**Comment by TheHappyKoala** [comment]
Merry Christmas to you, too 🚀 🌎 🎅 !!! 

Watching Kalle later on?

**Comment by HugoGranstrom** [comment]
😁😉 of course, like Julkalendern is it a tradition every year 🎁🎄🎅

**Comment by HugoGranstrom** [comment]
Karl-Bertil Jonsson in the evening as well is a must if one remembers 😂😅

**Comment by TheHappyKoala** [comment]
I stopped watching Kalle when I moved abroad after high-school, so I've kind of lost that tradition... If I have kids I'll make sure to tune in again, though 📺

**Comment by HugoGranstrom** [comment]
Tbh you aren't really missing a lot 😂😅 same thing every year except they are censoring some parts every few years. But it's oddly enough the thing that felt most like Christmas this year
