### ISSUE TITLE
NASA API update broke the simulator

### ISSUE THREAD

**Issue by lgommans** [TheHappyKoala/Harmony-of-the-Spheres#138]
The NASA API now returns invalid JSON data:

![first line is non-json](https://user-images.githubusercontent.com/5626710/116786251-e5fbbd80-aa9d-11eb-95f1-0c1235d0d817.png)

Notice the first line on the right.

A hotfix could be to, presumably [here](https://github.com/TheHappyKoala/Harmony-of-the-Spheres/blob/master/exoplanet-archive/exoplanetArchive.js#L20), add a line that skips this warning until we upgrade to this new system they offer. Or just grab the data and bundle it in the build perhaps, I'm not too clear on what this data does and whether it needs live updates from a space agency.

A workaround for users at the moment is to run this in your JavaScript console (F12, tab 'Console', you might have to type "allow pasting"):

    k="https://exoplanetarchive.ipac.caltech.edu/cgi-bin/nstedAPI/nph-nstedAPI?&table=exoplanets&select=pl_hostname,pl_pnum&where=pl_pnum>1 and st_mass>0 and st_rad>0&format=json";
    localStorage[k] = localStorage[k].substr(localStorage[k].indexOf("\n") + 1);

This removes the offending line from your cache in `localStorage`. If you now reload the page, it should work as expected.

**Comment by TheHappyKoala** [comment]
Hello! Thanks for highlighting this issue! You are correct in noting that the NASA Exoplanet Archive JSON API has been deprecated. To my knowledge, their new API doesn't support JSON, which is why we're now downloading all the data in the CSV format to produce new scenarios and textures. We're still working on adapting our code to fit the new API specifications, and have gotten to the point where we're creating new scenarios and planet textures on the basis of the data served by the new API, but nevertheless these modifications have not yet been pushed to the remote repository for the simple reason that the code is a royal mess. I'd be happy to commit this mess if you'd be willing to put up with it, and if you have time and feel like it, I would be super happy to have you help out with cleaning up this mess and making improvements where you see fit. I'm quite busy at the moment with work, but I'm still and intend to continue working on this project and would be super happy to help out with any questions / code review you might feel like launching my way :D.

**Comment by lgommans** [comment]
Hey, I love the simulator and thanks for all the work you already put into this :)

I found it a few days before it broke and linked it to some friends, then a few days later wanted to link it to someone else but noticed it didn't work anymore (since my browser deletes localStorage and cookies etc. from non-whitelisted sites regularly). I just figured out how to fix it and described it above for anyone else, because the sim is really quite something and everyone should get a chance to see the simulations, but I wasn't actually planning on getting into the project and developing it further. I'm just a random passer-by on the internet... :)

As a hotfix, though, so you have some time to just fix it whenever, you could make it skip the first line of the downloaded csv data (presumably [somewhere around here](https://github.com/TheHappyKoala/Harmony-of-the-Spheres/blob/master/exoplanet-archive/exoplanetArchive.js#L20)).

Oh and by the way, I just noticed the demo site is not linked with the repository's description. That's usually where most people would first look for it, I think. You can add it by clicking on the cog on the top right of the repository homepage (on desktop).

**Comment by TheHappyKoala** [comment]
Thanks for your very kind words and for sharing it with your buddies! 

Didn't cross my mind yesterday as it was quite late, but are you by any chance using the old version of the simulator that is hosted on GitHub? If so, that would explain quite a lot 🤣 .

There is a newer version of the simulator which you will find at https://www.gravitysimulator.org. It has all the exoplanetary systems discovered to date and procedurally generated textures for every single planet, and lots of other stuff that you won't find in the old version of the simulator.

**Comment by lgommans** [comment]
Oh! Well, the GitHub version is the one that popped up in duckduckgo, so yep that's the one I've been looking at. If there is a newer and better version, it might be worth linking that from the GH Pages variant or even making it just be a redirect :D

**Comment by TheHappyKoala** [comment]
Yups, that's an ace idea. Thanks for the heads-up!

**Comment by TheHappyKoala** [comment]
And... It's fixed: https://thehappykoala.github.io/Harmony-of-the-Spheres/

Might have to clear your browser cache, though (I had to).

**Comment by lgommans** [comment]
I didn't, but then my browser tends to be 'forgetful' about sites that aren't whitelisted to store data in it persistently :D

Anyway, that resolves the issue, thanks :)
