### ISSUE TITLE
Oh can I add a star scenario?

### ISSUE THREAD

**Issue by MarcGodard** [TheHappyKoala/Harmony-of-the-Spheres#144]
I would really like to add to this project. 

I have been researching (for fun only) stuff that we might be in a binary system with the star Sirius, and would love to simulate it.

https://www.tychos.info/citation/146D_Sirius-Precession-of-Solstice.pdf

We know the distance of Sirius, and assuming that ancient religions (the great year stuff) are right, it should take 24000 years to cycle it (precession measured now 26000 years, close to Sirius probably 22000 years?). Assuming year zero is the point furthest away from Sirius (before year zero it was always a red star in the historic records, and after its a blue star... Think Doppler effect for light.

Also, the rotation of the solar system would speed up as the starts approach the Barycenter of the system. Because most ancient texts use only 360 days a year, maybe the average over the period was 360 days (365 when we are far, and 355 when close?).

Anyway, I just want to model this idea for fun. Is this something if I build that would interest anyone?

Does anyone think that the speed of rotation would effect gravity? Maybe that is why all the ancient buildings are built with big stones? lol just a fun speculative questions.

**Comment by HugoGranstrom** [comment]
Hi, this was an intriguing topic I had never heard of before. 😄 It's totally not true, but fun to examine nonetheless. I'll comment on some of your claims though in the name of science ;)

> Assuming year zero is the point furthest away from Sirius (before year zero it was always a red star in the historic records, and after its a blue star... Think Doppler effect for light.

Mainly, Ptolemy is the one cited for listing Sirius in a list of red stars. But there are reasons to believe this is just something that got lost in translation or was added by mistake. Chinese astronomers who made observations before Ptolemy described Sirius as white so I think it's safe to say Sirius hasn't changed its color. Add to that the fact that as Sirius is such a bright star, it twinkles in all kinds of colors when the light is interfering with the atmosphere, and it's most notable when near the horizon. 

Regarding the orbital period, if we apply some Newtonian mechanics to it we can get a hunch of how long the orbital period of a Sirius-Sun system would be. I'm using the equation for [an elliptic orbit](https://en.wikipedia.org/wiki/Gravitational_two-body_problem): 

a^3 / T^2 = M → T = sqrt(a^3 / M) 

where a is the semi-major axis in AU and M is the total mass of the system in Solar masses. Sirius is 8.7 light years away, which a = 550 185 AU. The mass of the Sirius system is 2 solar masses for Sirius A, 1 solar mass for Sirius B (they are binary stars btw) and then the Sun with one solar mass → M = 4. This gives an orbital period of `T = 204048366 years`! That is 2*10^8 years, compared to the 2*10^4 years you proposed. So that system isn't even physically possible. Distance and orbital period is linked in such a way that you can't just use random distances and orbital together, they have to be related in a specific way. 

I don't mean to be harch and hope you don't take it so, but the first step in a simulation is to first test if the scenario is even physically possible. Which it isn't in this case 😄 


> Also, the rotation of the solar system would speed up as the stars approach the Barycenter of the system

Not sure what you mean here. The rotation of the solar system would probably be quite constant, but its movement in space would increase. If Earth suddenly fell into the Sun, the Moon wouldn't spin faster, but rather the Earth-Moon system would **move** faster as it approached. 

> Does anyone think that the speed of rotation would effect gravity? Maybe that is why all the ancient buildings are built with big stones? lol just a fun speculative questions.

That's something we can easily investigate with some calculations as well. Beware, the centrifugal force! 

Acceleration_centrifugal = ω^2 * r 

Currently for the earth we rotate 7.2921150 * 10^-5 radians/s and Earth's radius is 6378137 m at the equator. If we plug these number in we get a centrifugal acceleration of 0.0339 m/s^2 compared to the gravitational acceleration of 9.8 m/s^2. It's basically neglectable in other words. Earth would have to spin muuuuch faster for it to even be noticeable to living creatures. That could be an exercise for you, at which ω does the centrifugal force equal the gravitational? 😉 


> Anyway, I just want to model this idea for fun. Is this something if I build that would interest anyone?

There is a `Create New Scenario` [here](https://gravitysimulator.org/misc/create-new-gravity-simulation) which you could try out some ideas. But I'm afraid it doesn't have that much customizations yet. If you want an included scenario, then we would need a scenario that is actually possible to simulate 😄 Thank you once again for bringing this topic to my knowledge, it was interesting to try and debunk it :D

**Comment by HugoGranstrom** [comment]
Btw, I read up on `tychos.info` and I wouldn't precisely call it a reliable *scientific* source. Here's what they start off with:

> I hereby present the TYCHOS model, the only existing configuration of our “solar system” fully consistent with astronomical observation, physical reality and sheer logic. 

Any model starting with something along the lines of "this is the only model that describes ALL observations" most likely isn't that. If they really had such a superior model of the solar system, why haven't they submitted it for peer review to get it verified by experts? Our current models describe the universe (and in particular the Solar System) really really well. That site obviously has an agenda, to promote its own model of the solar system and as such everything you read there should be taken with a handful of salt.

**Comment by MarcGodard** [comment]
@HugoGranstrom, no offence taken, just having fun with all this.

I think the tychos.info site is really NOT good and their model is mostly nonsensical, and not basing this idea on that (even tho they reference that other document), its just where I found a shareable link for it (I have found a lot of interesting connecting sources from many books).

As far a Sirius being Red before 1CE, I looked through all the Chinese research on this a long time ago and all of them were post 1CE, nothing came up for pre 1CE in any primary source. (this doesn't mean you are wrong in any way, just sharing what I found). I did find the explanation you gave before when looking into this, however, found many sources in many ancient text books that say otherwise (I have a big collection of ancient text books--that you cannot find online--cause its fun and my hobby other than coding) and when exploring deeper to find confirming sources for your explanation I came up with nothing. Not only that, I found many research papers exploring this idea.

As far as the distance not working out, I appreciate the quick math (not my strongest of skills), but again, to me this is all fun, I want to see what it would take to make it work. There is also the possibility that we were in a binary (3 actually) system and we have long ago separated and Sirius is now out on its own.

This is the type of system I would think we are / were in: https://en.wikipedia.org/wiki/Gravitational_two-body_problem#/media/File:Orbit5.gif not an orbit (this is from your wiki link). If you look at that simulation, you see the 2 body speed up when they get closer (like a figure skater bringing in their arms they spin faster). This closes the needed distance to some degree, and also can explain the time with added speed.

Again, not saying this is the actual case, just thinking about what would be required for it to be true. All for fun.

I tried to build a simulation with this library and I couldn't do it. Unfortunately, typescript and react are both outside my tool set (I do mostly node back-end stuff). So not sure how i will manage with your code.

**Comment by HugoGranstrom** [comment]
> no offence taken, just having fun with all this.

Glad to hear :D although judging from the way you answered, it seems like I was a bit too offensive, so I'll take a chill pill now 😄 

> I think the tychos.info site is really NOT good and their model is mostly nonsensical, and not basing this idea on that (even tho they reference that other document), its just where I found a shareable link for something while searching (I have found a lot of interesting connecting sources from many books).

Gotcha! 👍 

> As far a Sirius being Red before 1CE, I looked through all the Chinese research on this a long time ago and all of them were post 1CE, nothing came up for pre 1CE in any primary source. (this doesn't mean you are wrong in any way, just sharing what I found). 

Here's a [paper](https://shc2000.sjtu.edu.cn/031207/sirius.htm) claiming that a historian called Sima Qian described Sirius as white 100BC. Maybe his works are one of the books you haven't read?

> I did find the explanation you gave before when looking into this, however, found many sources in many ancient text books that say otherwise (I have a big collection of ancient text books--that you cannot find online--cause its fun and my hobby other than coding) and when exploring deeper to find confirming sources for your explanation I came up with nothing. Not only that, I found many research papers exploring this idea.

These ancient text books, are they by any chance translated to a language that isn't their original language? Meanings of words can easily get lost in translation, as a word with multiple meanings might only be translated to convey one of those. I imagine words describing how things look to be especially prone to this. I found [this](https://armaghplanet.com/the-other-sirius-mystery-red-or-white.html) article which aims to debunk red Sirius which might be worth a read on this topic. Here's one paragraph:

> Pliny the Elder (23-79 AD) writing in his monumental work Natural History highlights many astronomical facts. He is often quoted as describing Sirius as reddish. He cites three heavenly bodies as ardens or igneus: the rising Sun, Mars, and Sirius. (Nat. Hist. II 18 47.)  A quick look at a translation (etymology) of these words reveals several meanings including burning, shinning, brilliant and fiery. I do not see that we can rely on this source for the actual colour of Sirius. Pliny could have been referring to the undisputed brightness and brilliance of Sirius.

When you said you found nothing to support my claim, which claim were you referring to more precisely? And what kind of evidence would you have expected to find? 

> As far as the distance not working out, I appreciate the quick math (not my strongest of skills), but again, to me this is all fun, I want to see what it would take to make it work. There is also the possibility that we were in a binary (3 actually) system and we have long ago separated and Sirius is now out on its own.

It's not impossible that the sun had sibling stars in the past that later separated. After all, stars usually form in bunches. As for what's required to make it work, I'll answer it to your next paragraph:

> This is the type of system I would think we are / were in: en.wikipedia.org/wiki/Gravitational_two-body_problem#/media/File:Orbit5.gif not an orbit (this is from your wiki link). If you look at that simulation, you see the 2 body speed up when they get closer (like a figure skater bringing in their arms they spin faster). This closes the needed distance to some degree, and also can explain the time with added speed.

The formula I used was in fact for the kind of orbit you described, the elliptic case where two bodies orbit their common center of mass. The two gifs actually are equivalent in a way, if you take the gifs where they move in circles and make their orbits ellipses instead, they will intersect if you stretch them in the right way and it will look like your linked gif. So the speedup is already taken into account in my previous calculation. Plus, it is not the fastest speed that decides the orbital period the most, it is the slowest speed. For example: If you run at the speed of light the first half of a race and walk the rest. It won't make much of a difference on your final time if you *just* ran at half the speed of light instead as the walking is what is taking the majority of the time. 

> Again, not saying this is the actual case, just thinking about what would be required for it to be true. All for fun

So to answer your previous question, it isn't possible (with Newton's law of gravity) for such a system to exist with such great distances (8.7 ly) and short orbital periods (25000 years), at all. The speed it would require would be too high for it to even be in orbit at that distance. 

> I tried to build a simulation with this library and I couldn't do it. Unfortunately, typescript and react are both outside my tool set (I do mostly node back-end stuff) and the simulator builder wasn't easy to figure out. So not sure how i will manage with your code.

Building an impossible simulation does sound hard even in the best of software 😉 But yes, if you aren't familiar with the code it can be pretty daunting to even try. I haven't used the simulation builder much myself either and setting up systems with precise initial conditions is virtually impossible with it as well. The good thing is that you don't have to deal with it anymore though, as it's impossible... 🙃

**Comment by MarcGodard** [comment]
@HugoGranstrom 

> Glad to hear :D although judging from the way you answered, it seems like I was a bit too offensive, so I'll take a chill pill now 😄

Hahaha no, english is my 2nd language, I apologize for any rudeness, it wasn't intended.

> Here's a paper claiming that a historian called Sima Qian described Sirius as white 100BC. Maybe his works are one of the books you haven't read?

I actually read that before, but 100BC when it comes to 24k year cycle (or more) the star would have been already mostly slowed (therefore mostly white at that point). Most of the text I am referring too were 1000s of years old.

> These ancient text books, are they by any chance translated to a language that isn't their original language?

Most have the original language, then the English interpretation.

> Meanings of words can easily get lost in translation, as a word with multiple meanings might only be translated to convey one of those. I imagine words describing how things look to be especially prone to this.

I speak 7 languages. I think I understand this better than most. lol

> I found this article which aims to debunk red Sirius which might be worth a read on this topic.

This article is new to me, but their claim I have seen many times while trying to debunk this myself. The problem I have noticed is that all the debunks on this, only make that one claim, but references to Sirius being red are plentiful, so to me, reading the same debunking over and over, shows that people didn't do enough research, or they are on purpose picking the easier to debunk and ignoring all the references that are harder to debunk. But I appreciate the effort.

> it isn't possible (with Newton's law of gravity) for such a system to exist with such great distances (8.7 ly)

https://en.wikipedia.org/wiki/AR_Cassiopeiae is a 7 star system. Not sure the ly span, but we are constantly surprised by things that we thought were impossible when it comes to space, so don't take offence, but saying it is not possible just isn't enough. I am trying to figure out what variables CAN make it possible.

> short orbital periods (25000 years), at all. The speed it would require would be too high for it to even be in orbit at that distance.

Again, this might just be the case, but looking at what can make it possible. Maybe it is 240 000k years, i don't know.

> The good thing is that you don't have to deal with it anymore though, as it's impossible... 

Hahaha, saying it is impossible isn't an answer to me. This is not how science and discovery is done. One last time, not looking to see if this is the case, looking to see what needs to be done to make it the case, so it can be compared.

**Comment by HugoGranstrom** [comment]
> Hahaha no, english is my 2nd language, I apologize for any rudeness, it wasn't intended.

English isn't mine either :) You didn't sound rude at all, it was more the opposite actually. You felt a little defensive like I had been the rude one :P

> I actually read that before, but 100BC when it comes to 24k year cycle (or more) the star would have been already mostly slowed (therefore mostly white at that point). Most of the text I am referring too were 1000s of years old.

How old are your oldest records claiming Sirius is red? And are we using the same year notation? Let's just use negative numbers for years before year 0. So Qian is from year -100, when are your sources from? :) But as the 24k year cycle is way too small to be physically possible, the much longer orbital period would make the difference in speed over a couple of hundred years neglectable. It especially wouldn't be able to produce the redshift needed to make it appear red just a few hundred years before Qian at least. (The speeds are sloooow at the furthest distance).

> Most have the original language, then the English interpretation.
> I speak 7 languages. I think I understand this better than most. lol

Impressive!🤯 Then you are my best source for their meanings ;) How is Sirius' color mostly described? Is it clear they mean "red" or is it more vague like "Sirius is like fire"?

> This article is new to me, but their claim I have seen many times while trying to debunk this myself. The problem I have noticed is that all the debunks on this, only make that one claim, but references to Sirius being red are plentiful, so to me, reading the same debunking over and over, shows that people didn't do enough research, or they are on purpose picking the easier to debunk and ignoring all the references that are harder to debunk. But I appreciate the effort.

Judging from the author of the article, they debunked the sources most used by their opposition. Another thing to keep in mind as well: are the sources depending on each other? Are many of them based on a single source for example. It's the sources that have made their own observations that are the most interesting. Mind giving me a reference people often don't want to try and debunk? :D

> en.wikipedia.org/wiki/AR_Cassiopeiae is a 7 star system. Not sure the ly span, but we are constantly surprised by things that we thought were impossible when it comes to space, so don't take offence, but saying it is not possible just isn't enough. I am trying to figure out what variables CAN make it possible.

[Here's](https://astronomy.stackexchange.com/questions/10108/how-do-the-orbits-of-nu-scorpii-and-ar-cassiopeiae-work) a link if you are curious about how exactly they are structured. Not sure what you are trying to convey with that example, Newton's law of gravity says nothing about how many stars can orbit each other. It does tell us about **how** they can orbit each other on another hand. And that is the point I'm trying to pass on: I'm saying the variables you provided me with aren't possible because they don't make the equation work. Simple as that. There are no equations preventing 7-star systems so no real connection between these two things in my mind. If you want to know what CAN make it possible, I have provided you with both the answer and the formula to try it out yourself in my first message 😉 We know the masses, we know the distance, only the orbital period is unknown. I calculated it to 25 **million** years as a best-case scenario. In the link above the largest orbital period is 300k years so it's still huge comparatively with the largest known orbital period. I'm honestly not sure exactly what you want to figure out anymore as the configuration you stated initially *is impossible* 😅 Do you want a specific orbital period or a specific distance? You can only choose one as the other depends on the chosen one. 

> Again, this might just be the case, but looking at what can make it possible. Maybe it is 240 000k years, i don't know

25 million years makes it possible 😄 Also worth remembering is that Alpha Centauri is closer to us and has a larger gravitational pull on our Solar System than Sirius has. 

> Hahaha, saying it is impossible isn't an answer to me. This is not how science and discovery is done. 

According to Newton's law of gravity, it is IMPOSSIBLE for that combination of distance and time. (assuming the Sun and Sirius is a long-distance binary). That is a fact using our current knowledge of science. And our gravity simulator uses Newton's law of gravity to do the simulation so it is impossible for us to simulate it as well. If it on the other hand would be true, then we would need another description of the universe than we currently have. And no, General Relativity doesn't help you. Science is done by finding better and better models of the universe and the current one is the best we have and it says it is impossible. If you can PROVE that Sirius does in fact not behave as predicted, then we can talk about science and discovery. :)

> One last time, not looking to see if this is the case, looking to see what needs to be done to make it the case, so it can be compared.

One last time, I have already given you both the answer and the equation to find out yourself how to make it possible. What are you comparing it to? The 25k year cycle? 😄

**Comment by MarcGodard** [comment]
Please don't take this the wrong way, but you do not seem to understand what I am asking. Thanks for the effort, but I will wait for someone else to answer while I am also seeking other sources that do not seem so closed to this fun problem. Cheers.

**Comment by HugoGranstrom** [comment]
Indeed, we are clearly not on the same wavelength 😃 I don't know if it's because I'm coming in from a very academic point of view and you a more non-academic view? Maybe it's my maths that's just removing all the fun for you? I'm getting the impression you aren't interested in the actual physics, and more the idea of a universe that could have been. 

I would very much want to try and understand what you mean though as you seem to be able to unlink your thinking from the physics behind it. Would you mind giving it a last try? Just the core question without any debates around ancient sources and what they say or debunking this and that. Just the basic idea you want to explore? And most importantly, exactly what it is that you want in an answer. Just to discuss ideas that might or might not be physically possible without any maths? Or do you want some math as well to help you understand the working of orbital mechanics so you can try and understand which orbits are and aren't possible? 

Nonetheless, I would very much like to read the answers of other people if you manage to get the answers you seek from anyone else out there on the wonderful thing that is the internet 😄 Cheers!

**Comment by MarcGodard** [comment]
> Indeed, we are clearly not on the same wavelength 😃 I don't know if it's because I'm coming in from a very academic point of view and you a more non-academic view? Maybe it's my maths that's just removing all the fun for you? I'm getting the impression you aren't interested in the actual physics, and more the idea of a universe that could have been.

I was offered to do my PhD at 3 schools, and turned it all down. Most academics I knew, knew very little outside their own field. As an autodidact and polyglot I found them mostly frustrating and lacked imagination (which is why they all loved my research and ideas, because I see things from a different perspective). Not that I claim to be like any of the famous researchers of the past, but every single one of them explored many fields and ideas (even dumb ideas).

The problem isn't the math, I understand what you are saying, you just do not understand what I am asking. I am asking out of all the variables (speed, distance, masses, etc...) what would need to be changed to make the scenario possible (from unlikely to likely possible changes). But you insist it is simply impossible, therefore you do not understand. I am not un-linking from physics, however, I do think we might have some physics incorrect (I think gravity is very misunderstood--even if formulas do work). I am an explorer of ideas, and possibilities, but am well grounded generally speaking.

Once I know the variables that do not currently work or need to be, I can explore those and see which can work. This is just for fun, I mostly retired many years ago and this is what I do to keep my mind strong.

I have a few data scientist that I work with, usually, but they are all more concerned with the covid data (https://www.pandata.org/ as an example). My degree is psychology and computer science with philosophy, so math is usually my weakest point (unless it is data mining).

**Comment by HugoGranstrom** [comment]
> I was offered to do my PhD at 3 schools, and turned it all down. Most academics I knew, knew very little outside their own field. As an autodidact and polyglot I found them mostly frustrating and lacked imagination (which is why they all loved my research and ideas, because I see things from a different perspective). Not that I claim to be like any of the famous researchers of the past, but every single one of them explored many fields and ideas (even dumb ideas).

I agree mostly that academia today is very focused on their specialized fields, as we have come so far in science that, that specialization is needed. But we also need visionaries that can think outside the box like the old great scientist. Both are needed, but perhaps the academically inclined scientist don't discuss enough with more open-minded people like you.

> The problem isn't the math, I understand what you are saying, you just do not understand what I am asking. I am asking out of all the variables (speed, distance, masses, etc...) what would need to be changed to make the scenario possible (from unlikely to likely possible changes). But you insist it is simply impossible, therefore you do not understand. I am not un-linking from physics, however, I do think we might have some physics incorrect (I think gravity is very misunderstood--even if formulas do work). I am an explorer of ideas, and possibilities, but am well grounded generally speaking.

This is the thing that I'm lost on at the moment, what are the specifications for "the scenario"? If we use our best knowledge of orbital mechanics, we only need 3 variables (or really 2 as the third depends on the first 2) to describe the characteristics of an orbit: distance, mass, and orbital period. Two of those, we think we have a pretty good idea of: the masses and the distance. So any scenario with a different orbital period than 25 million years would require us to radically change either one or both of these "establish values". That is why I claim it to be impossible, because we would have to throw our current science in the trash bin. Are we on the same page here? I think a more precise specification of exactly what you want your scenario to be would help to give you these "non-scientific" values though. Is it the orbital period that would be the most important to match for example?

Gravity sure is the force we have the worst knowledge of, but judging from the fact that we've got spacecraft zooming around the solar system I'd say we have a quite good idea at least. But something is weird with dark matter and dark energy. 

> Once I know the variables that do not currently work or need to be, I can explore those and see which can work. This is just for fun, I mostly retired many years ago and this is what I do to keep my mind strong.

As I've said, mass, distance and orbital period are the only variables you need (you can use orbital elements as well but that's too advanced in this case). Speed and the others are varying over the span of the orbit but it could be calculated from those values, in theory. So I'm sad to say that there isn't much exploring of parameters (only these 3) if you are working with our current framework of gravity 🤷 

> I have a few data scientist that I work with, usually, but they are all more concerned with the covid data (pandata.org as an example). My degree is psychology and computer science with philosophy, so math is usually my weakest point (unless it is data mining).

That sounds interesting! :D

**Comment by MarcGodard** [comment]
> I agree mostly that academia today is very focused on their specialized fields, as we have come so far in science that, that specialization is needed.

Needed, yes, having it be the totality, no.

> of orbital mechanics, we only need 3 variables

Not really. Have you ever looked into the plasma cosmology stuff? (don't send me debunks, I have seen most). Like all fringe groups, it's bound to attract lots of fringe people with fringe ideas, but the base science of it looks really interesting. Their ideas remove the need for dark matter and dark energy or at the very least alters their need a lot. Imagine, billions and billions of dollars spent on "proving" dark matter / energy to date, nothing substantial. And I am sure, something will / has fallen into a local minima of "proof" and distributed as truth at some point. So many things fall into that. On the spectrum of truth there are things that look like truth but aren't, things that are truth, an infinite amount of things that fall between looking like truth and being false, and an infinite amount of things that are false, and look false.

Everything is questionable (but not discard-able).

I once read a great set of "research" on dinosaurs and how the gravity would have to be much lighter to account for everything from wing spans, known bone density, and so on. Of course there could easily be other factors to account for this perceived need, but their argument was logical, sound, and very interesting.

This above is to say the known masses of stars may be wrong (another variable) and gravity may very well be wrong (again, another--perhaps our formulas for gravity work very well near objects like planetary bodies--spaceships--but not so well in the vacuum of space). I am the last person to proclaim to know anything, if anything the more I explore, the more I realize I know nothing.

Before you continue and say "So many academics can't be wrong" look into history and you will see plenty (just look at covid as an example, does all that make "sense" to you?).

The idea is to always look at things from outside the accepted overton window. Its like giving someone a false dichotomy. At the start of covid (after google released their mobility data) we ran a bunch of correlations on death with mobility and 1000s of other data we have for the world. The only correlations that were not noise were access to media, and broadband internet. Sure sounds like the noceebo effect to me. We ran those correlations again a few months ago, and it correlated to sanitation (more access to sanitation === more covid deaths). Yes the academics are all saying to sterilize everything and wear masks.

We also found tons of research suggesting the same thing (nurses with more kids, families with more pets--less likely).

My point with all this is that I have learned many times over again that the academics are usually wrong. Another interesting thing is I reversed type 2 diabetes, fatty liver disease, and other major health issues with an all red-meat diet (also lost a lot of weight). Did the opposite my doctor told me, but due to the pharma capturing the regulatory body, they sure are against red meat and doctors are glorified pill pushers now.

Anyway, approach this idea with a question everything mind-set. I am trying to see if the ancient texts (that really understood the sky better than we do) are telling us something we are missing. That is all, just exploring the space of questioning.

**Comment by MarcGodard** [comment]
@HugoGranstrom I would love your thoughts

**Comment by HugoGranstrom** [comment]
I won't have a reliable internet connection until the weekend, I'll get back to you then :)

**Comment by HugoGranstrom** [comment]
> Needed, yes, having it be the totality, no.

Agreed! 👍 

> Not really. Have you ever looked into the plasma cosmology stuff? (don't send me debunks, I have seen most). Like all fringe groups, it's bound to attract lots of fringe people with fringe ideas, but the base science of it looks really interesting. Their ideas remove the need for dark matter and dark energy or at the very least alters their need a lot. 

You could have just told me from the beginning you wanted to discuss alternative (== non-mainstream) physics, then we could have spared ourselves a lot of meaningless discussions 😛 Haven't heard about it before and judging from the Wikipedia article not much work has been put into it since the 90s. Interesting and mind-tingling indeed, but if it doesn't comply with the observations we've made (the CMB, most notably) then it won't really help us understand the universe further 🤷 

> Imagine, billions and billions of dollars spent on "proving" dark matter / energy to date, nothing substantial. 

I think we have different views on "proving" dark matter / energy. I see it more like we are investigating whether or not it could be a solution, and the only way to know is by doing studies and seeing if they comply with our models or not. And finding nothing is also a result in and of itself, but it doesn't rule out *all* options, which is quite frustrating tbh. And as it stands, the dark matter + energy is the **currently** best model we have that describes the most of what we see out there in the universe. That isn't to say it is the final model, it most certainly isn't. We have to test our current models over and over again to find the areas where they don't work, because those will tell us how to improve the model. 

> And I am sure, something will / has fallen into a local minima of "proof" and distributed as truth at some point. So many things fall into that. On the spectrum of truth there are things that look like truth but aren't, things that are truth, an infinite amount of things that fall between looking like truth and being false, and an infinite amount of things that are false, and look false.

I agree partly, but what would we teach if not the cutting edge of our knowledge? We should of course be totally transparent about the parts we aren't certain about. The astronomy courses I've taken have all been very explicit that dark matter / energy is just our **current best guess** and they've mentioned a few other alternative models like Modified Newtonian Gravity that haven't managed to match the observations equally well. We will probably never manage to get a perfect description of the universe, but we will find pretty darn good models if we just follow the scientific method. 

> The only correlations that were not noise were access to media, and broadband internet. Sure sounds like the noceebo effect to me. We ran those correlations again a few months ago, and it correlated to sanitation (more access to sanitation === more covid deaths). Yes the academics are all saying to sterilize everything and wear masks.

I haven't looked at the data myself but you sure know that correlation between two variables doesn't mean there is a cause-and-effect relationship between them. They could very well just depend on a common variable. As I've said, I haven't looked at the data myself but one theoretical reason could be that the countries with access to sanitation are more likely to be countries that report a larger percent of the cases, because they are more high-income and have the systems set up for that. That's just an uneducated guess though. Another could be that access to sanitation exposes us to less microbes when we are kids and thus our immune systems are weaker generally here. Another hobby-psychology theory of mine is that people who sanitize often and wear masks get a false sense of safety and ignore the most effective protection: to keep your distance from others. In other words, it mustn't be that the act of sanitation right now that causes the correlation. Sterilization kills microbes, that is a fact and has saved millions of people over the years, so I have a hard time imagining sterilization itself causes death by covid as it kills covid viruses. It might be related in other non-direct ways though, but it still doesn't mean we shouldn't wash our hands and wear masks. 

Would love to hear from someone in charge comment on this though and how they explain it, so if you manage to dig something up, let me know :)

> My point with all this is that I have learned many times over again that the academics are usually wrong. 

That is quite a big statement to say that most of the academics are wrong with just one perhaps-not-true example. Sometimes academics are wrong, sure. But saying that most academics are wrong is just ignorant towards all the advances that have been made in science over the years. It's a totally different thing if you just **feel** like they are wrong often, that could probably be explained by exceptionalism. Nobody wants to report "Scientists was correct as expected" while "Scientists was incorrect!!!" is much more clickable and sellable. It should be noted I have heard of the occurrences of non-reproducible papers **in psychology** specifically. 

> Another interesting thing is I reversed type 2 diabetes, fatty liver disease, and other major health issues with an all red-meat diet (also lost a lot of weight). Did the opposite my doctor told me, but due to the pharma capturing the regulatory body, they sure are against red meat and doctors are glorified pill pushers now.

First of all, I'm glad you managed to get healthy! 😃 As far as I've understood it, red meat is more about the long-term effects and obesity has a much more direct impact on one's health. So I wouldn't say it proves anything, the loss of weight was probably the major factor in your recovery, I doubt the red meat had any effect at all during that "short" time. Also, I wouldn't call doing 1/2 of the doctor's advice as doing the opposite of it 😛 (or wasn't losing weight part of their prescription?)


> Anyway, approach this idea with a question everything mind-set. I am trying to see if the ancient texts (**that really understood the sky better than we do**) are telling us something we are missing. That is all, just exploring the space of questioning.

That is just pure speculation on your part. They also invented astrology, so I'm not sure I agree with you on this one. Nowadays we have vastly superior abilities to study the skies every night and log it, so I'd say we have a much better understanding of the sky than they ever had 🤓  

But sure, exploring the idea that we might have missed something they saw is a fun idea. You just have to find someone who is more familiar to alternative physics if you want a framework to test them within, because Newtonian gravity doesn't work with them 😄

**Comment by MarcGodard** [comment]
I am just going to leave these here for you:

https://www.pandata.org/time-to-reopen-society/

https://www.covidchartsquiz.com/

But to me covid is boring. Its just government power + big pharma... meh... ancient texts mixed with cosmology is interesting.

Here is more for meat:

https://www.youtube.com/watch?v=sGG-A80Tl5g

https://www.youtube.com/watch?v=1MH2ZKt35K4

Don't take this the wrong way, but academics today have pretty much proven all the past academics wrong on most things... what makes you think this isn't still the case in 20 years? I remember every year hearing in university many times that the previous years material was over simplified and mostly wrong. When I rejected doing my PhD, my current supervisor asked me why and I said "I have never seen so many smart dumb people before, I don't want that".

Explore a bit more. I would continue, but you seem to dismiss my views so simply as if I know little or understand little (like the covid correlations, I know correlation don't mean causation, and the data we have covers so much that it would make your head spin, yet you act like your simplistic explanation wasn't thought about). https://www.youtube.com/watch?v=rlBr2wae2Go <--- a friend of mine that works with Pandata (linked in a previous post that you have spent zero time looking at before commenting). See if you understand any of that video.

Instead of simply searching and adding the word debunk, perhaps spend some time with something novel (like this: https://55theses.org/2011/03/18/thesis-1/ or many many other things) before you feel you know something about it. This is the problem with academics, they think they know stuff too easily (and its why they are alway stuck in local minima defending old garbage that many grew past-- https://www.chemistryworld.com/news/science-really-does-advance-one-funeral-at-a-time-study-suggests/3010961.article ). Did you know that doctors and nurses were 7 times more likely than the average to join the nazi party? Think about why... (not calling you a nazi in any way, just an interesting fact that when understood reveals a lot).

Anyway, good luck if you choose to pursue anything that makes you currently unconformable. To me academia is the alternative.

**Comment by HugoGranstrom** [comment]
> But to me covid is boring. Its just government power + big pharma... meh... ancient texts mixed with cosmology is interesting.

I mean, we have totally different views on this then. I don't know how it has been where you live but here in Sweden (as was mentioned in the linked video), we didn't have a (hard) lockdown. But if you had one, I can understand your view but I disagree with you. I don't believe it's big pharma that is behind the lockdowns, just panicked and overprotective governments (in most cases, some countries like China surely took the chance to suppress their people even more). 

> Don't take this the wrong way, but academics today have pretty much proven all the past academics wrong on most things... what makes you think this isn't still the case in 20 years?

That is how science works! You take steps towards the truth, so naturally, we will go from simpler models to more advanced models over time. If you know of a way to get to the final truth in one single step, please tell me. Also, "proving wrong" is a bad phrasing of it IMO. The old models worked (most of them), but were limited in most cases and have since then been expanded or replaced by better models. They were not wrong, just not as good as today. For example: Newtonian gravity is a really useful tool still even though it was superseded by the more accurate General Relativity. So I hope we will be proven "wrong" (I hope we will have improved our models) in 20 years! 😉  

It feels like we both have already cemented our views regarding academia so I see no reason for us to continue on this route as we likely will only waste both of our's time without making any progress. 

I'm sorry if I said something that felt like it tried to minimize your intellect, the way you expressed the sanitization-mortality correlation insinuated to me, that you thought it was clear causation between them. But I'm glad that wasn't the case. 

> Anyway, good luck if you choose to pursue anything that makes you currently unconformable. To me academia is the alternative.

Lucky you that the "academic alternatives" have helped make our lives easier then, for example, the device you are writing this on right now probably wouldn't have been possible without the academics finding out how electromagnetism works for one and doing the material science required to build the computer chips to name a few...

Have a nice life and hope you stay healthy Marc! You have definitely broadened my mind with these discussions and I'll take with me a more skeptical view of things.

**Comment by MarcGodard** [comment]
> I don't believe it's big pharma that is behind the lockdowns

My wife works for international pharma companies (many of them) as a very high up consultant. You can believe what you want though, because believing is science. I don't think its JUST big pharma and gov. World Economic Forum, Event 201, and so on. Still boring tho. People want to rule the world ladida ladida, who cares.

> Also, "proving wrong" is a bad phrasing of it IMO

Agreed, but descriptively correct.

> we both have already cemented our views regarding academia

Mine are not cemented, nothing wrong with academia when you understand how it works. I just don't find its current iteration very good. Publish or peril, looking at the smallest parts of system and never the big parts, can't lose your funding from big gov so your conclusions need to be politically correct.

> the device you are writing this on right now probably wouldn't have been possible without the academics

That is as fallacious as correlations = causation and I had already extended my view of you beyond such things, I guess I made a mistake.

The world is such an interesting place, unfortunately some people are stuck thinking it isn't.
